import { Poppins } from "next/font/google";
import "./globals.css";

import Header from "./components/Header/Header.jsx";
import Footer from "./components/Footer/Footer.jsx";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Birmingham Business",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/BBLogo.png" sizes="any" />
      <body className={poppins.className} id="bodyId">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
