import { Poppins } from "next/font/google";
import "./globals.css";
import Script from "next/script";

import Header from "./components/Header/Header.jsx";
import Footer from "./components/Footer/Footer.jsx";
import SkipLink from "./components/SkipLink/SkipLink.jsx";

const poppins = Poppins({
	weight: ["300", "400", "500", "600", "700"],
	subsets: ["latin"],
});

export const metadata = {
	title: "Birmingham Business",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<Script
				strategy="afterInteractive"
				src="https://plausible.io/js/script.js"
				defer
				data-domain="birmingham-biz-kappa.vercel.app"
			/>
			<link rel="icon" href="/BBLogo.png" sizes="any" />
			<body className={poppins.className} id="bodyId">
				<SkipLink targetId="maincontent"/>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
